---
type: object
properties:
  distance:
    type: number
    minimum: 0
  offer:
    type: object
    properties:
      offer_type:
        type: string
      offer_val:
        type: 
        - number
        minimum: 0
  order_items:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          minimum: 0
          maximum: 500000
        quantity:
          type: number
          minimum: 1
required:
- order_items
- distance
